"""initial_schema

Revision ID: 1447770f95b4
Revises: 
Create Date: 2025-03-15 21:17:14.103960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1447770f95b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('publication_dt', sa.DateTime(), nullable=True),
    sa.Column('updated_dt', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('featured_image', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.String(length=255), nullable=True),
    sa.Column('reading_time', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_slug'), 'blog', ['slug'], unique=True)
    op.create_index(op.f('ix_blog_status'), 'blog', ['status'], unique=False)
    op.create_table('contact',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('submission_dt', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('new', 'read', 'replied', 'archived')", name='status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_status'), 'contact', ['status'], unique=False)
    op.create_index(op.f('ix_contact_submission_dt'), 'contact', ['submission_dt'], unique=False)
    op.create_table('tag',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_code', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('blog_tag',
    sa.Column('blog_id', postgresql.UUID(), nullable=False),
    sa.Column('tag_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_id', 'tag_id')
    )
    op.create_table('related_blog',
    sa.Column('source_blog_id', postgresql.UUID(), nullable=False),
    sa.Column('related_blog_id', postgresql.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.CheckConstraint('source_blog_id != related_blog_id', name='different_blogs'),
    sa.ForeignKeyConstraint(['related_blog_id'], ['blog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_blog_id'], ['blog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_blog_id', 'related_blog_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_blog')
    op.drop_table('blog_tag')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_contact_submission_dt'), table_name='contact')
    op.drop_index(op.f('ix_contact_status'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_blog_status'), table_name='blog')
    op.drop_index(op.f('ix_blog_slug'), table_name='blog')
    op.drop_table('blog')
    # ### end Alembic commands ###
