"""fix_uuid_handling_v3

Revision ID: 158cfa050aa4
Revises: 5449eccfc95d
Create Date: 2025-03-29 15:05:40.821636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158cfa050aa4'
down_revision = '5449eccfc95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
