"""test

Revision ID: 356d13377862
Revises: 158cfa050aa4
Create Date: 2025-03-29 15:09:44.604017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356d13377862'
down_revision = '158cfa050aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('slu', sa.String(length=255), nullable=False))
    op.drop_index('ix_blog_slug', table_name='blog')
    op.create_index(op.f('ix_blog_slu'), 'blog', ['slu'], unique=True)
    op.drop_column('blog', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_blog_slu'), table_name='blog')
    op.create_index('ix_blog_slug', 'blog', ['slug'], unique=False)
    op.drop_column('blog', 'slu')
    # ### end Alembic commands ###
