"""fix_uuid_handling_v2

Revision ID: 5449eccfc95d
Revises: 56b5efe0b571
Create Date: 2025-03-29 14:12:52.682372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5449eccfc95d'
down_revision = '56b5efe0b571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
