"""fix_uuid_handling_v2

Revision ID: 56b5efe0b571
Revises: e914d4e39682
Create Date: 2025-03-29 14:08:31.426460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b5efe0b571'
down_revision = 'e914d4e39682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
