"""fix_uuid_handling

Revision ID: 8de808f7e452
Revises: dacd0d3b3e3f
Create Date: 2025-03-29 13:52:02.647150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8de808f7e452'
down_revision = 'dacd0d3b3e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_unique_constraint(None, 'user', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_column('user', 'uuid')
    # ### end Alembic commands ###
