"""reverting test

Revision ID: c036a9595cc3
Revises: 356d13377862
Create Date: 2025-03-30 12:38:12.869559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c036a9595cc3'
down_revision = '356d13377862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('slug', sa.String(length=255), nullable=False))
    op.drop_index('ix_blog_slu', table_name='blog')
    op.create_index(op.f('ix_blog_slug'), 'blog', ['slug'], unique=True)
    op.drop_column('blog', 'slu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('slu', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_blog_slug'), table_name='blog')
    op.create_index('ix_blog_slu', 'blog', ['slu'], unique=False)
    op.drop_column('blog', 'slug')
    # ### end Alembic commands ###
