"""fix_uuid_handling_v2

Revision ID: e914d4e39682
Revises: 8de808f7e452
Create Date: 2025-03-29 13:55:14.681107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e914d4e39682'
down_revision = '8de808f7e452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
